Repository VulcanoCorp/Vulcano, pull requests merged in 2021-11, with the labels that each got.

#9 Feature/form screens
  src/Main.java
  src/View/BaseView.java
  src/View/View.java
Labels: Front-end

#10 Model
  README.md
  docs/DER_Vulcano.pdf
  docs/MER_Vulcano.pdf
  docs/Script_Vulcano.sql
  img.png
  src/Model/Project.java
  src/Model/Requirements.java
  src/Model/User.java
Labels: Back-end

#11 ajustes de layout e verificacoes
  src/View/BaseView.java
  src/View/View.java
Labels: Front-end

#12 UserDAO
  src/Connection/BaseDAO.java
  src/DAO/UserDAO.java
Labels: DataBase, Back-end

#13 Feature/requirement dao
  src/DAO/RequirementDAO.java
  src/Main.java
  src/Model/Requirements.java
  src/View/View.java
Labels: Back-end

#14 adding session controller
  src/Controller/SessionController.java
Labels: Back-end

#15 login + ajustes
  src/DAO/RequirementDAO.java
  src/View/View.java
Labels: Front-end

#18 Inclusão da classe ProjecDAO
  src/DAO/ProjectDAO.java
  src/DAO/UserDAO.java
  src/Model/Project.java
Labels: Back-end

#19 fix requirement reference and user dao
  src/Controller/SessionController.java
  src/DAO/UserDAO.java
  src/View/View.java
Labels: Back-end

#16 userControler
  src/Controller/UserControler.java
Labels: Back-end

#21 Criação da ProjectController
  src/Controller/ProjectController.java
Labels: Back-end

#22 requirement crude implementation on view
  src/Controller/ProjectController.java
  src/Controller/RequirementController.java
  src/Controller/UserControler.java
  src/DAO/RequirementDAO.java
  src/DAO/UserDAO.java
  src/View/View.java
Labels: Front-end

#24 Ajustes e correções
  docs/Diagrama de Classe Vulcano.png
  docs/Script_Vulcano.sql
  src/Controller/ProjectController.java
  src/Controller/RequirementController.java
  src/Controller/SessionController.java
  src/Controller/UserController.java
  src/DAO/ProjectDAO.java
  src/DAO/RequirementDAO.java
  src/Model/Requirement.java
  src/View/BaseView.java
  src/View/View.java
Labels: DataBase, Back-end, Front-end

#26 Correção das merdas do Victor
  docs/Script_Vulcano.sql
  resource/vulcano.png
  src/View/View.java
Labels: DataBase, Back-end, Front-end
